-- MySQL Script generated by MySQL Workbench
-- Wed Dec 20 15:07:13 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SM
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SM` ;

-- -----------------------------------------------------
-- Schema SM
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SM` DEFAULT CHARACTER SET utf8 ;
USE `SM` ;


-- -----------------------------------------------------
-- Table `SM`.`Professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SM`.`Professor` ;

CREATE TABLE IF NOT EXISTS `SM`.`Professor` (
  `Username` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Regente` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Username`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SM`.`Sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SM`.`Sala` ;

CREATE TABLE IF NOT EXISTS `SM`.`Sala` (
  `idSala` VARCHAR(10) NOT NULL,
  `MaxLugares` INT NOT NULL,
  PRIMARY KEY (`idSala`),
  UNIQUE INDEX `idSala_UNIQUE` (`idSala` ASC))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SM`.`UCLicenciatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SM`.`UCLicenciatura` ;

CREATE TABLE IF NOT EXISTS `SM`.`UCLicenciatura` (
  `codigoUC` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigoUC`),
  CONSTRAINT `fk_UCLicenciatura_UC1`
    FOREIGN KEY (`codigoUC`)
    REFERENCES `SM`.`UC` (`codigoUC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SM`.`UCComplementar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SM`.`UCComplementar` ;

CREATE TABLE IF NOT EXISTS `SM`.`UCComplementar` (
  `codigoUCComp` VARCHAR(45) NOT NULL,
  `diaSemana` VARCHAR(5) NOT NULL,
  `Per` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`codigoUCComp`),
  UNIQUE INDEX `UC_codigoUC_UNIQUE` (`codigoUCComp` ASC),
  CONSTRAINT `fk_UCComplementar_UC1`
    FOREIGN KEY (`codigoUCComp`)
    REFERENCES `SM`.`UC` (`codigoUC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SM`.`UCPerfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SM`.`UCPerfil` ;

CREATE TABLE IF NOT EXISTS `SM`.`UCPerfil` (
  `codigoUCPerfil` VARCHAR(45) NOT NULL,
  `diaSemana` VARCHAR(5) NOT NULL,
  `idPerfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigoUCPerfil`),
  UNIQUE INDEX `UC_codigoUC_UNIQUE` (`codigoUCPerfil` ASC),
  INDEX `fk_UCPerfil_Perfil1_idx` (`idPerfil` ASC),
  CONSTRAINT `fk_UCPerfil_UC1`
    FOREIGN KEY (`codigoUCPerfil`)
    REFERENCES `SM`.`UC` (`codigoUC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_UCPerfil_Perfil1`
    FOREIGN KEY (`idPerfil`)
    REFERENCES `SM`.`Perfil` (`idPerfil`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SM`.`Turno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SM`.`Turno` ;

CREATE TABLE IF NOT EXISTS `SM`.`Turno` (
  `idTurno` VARCHAR(45) NOT NULL,
  `codigoUC` VARCHAR(45) NOT NULL,
  `Hora` TIME(0) NOT NULL,
  `idSala` VARCHAR(10) NOT NULL,
  `UsernameProf` VARCHAR(45) NOT NULL,
  `maxAlunos` INT NULL,
  `Tipo` VARCHAR(10) NOT NULL,
  `Aulas` INT NOT NULL,
  `diaSemana` VARCHAR(5) NULL,
  PRIMARY KEY (`idTurno`, `codigoUC`),
  INDEX `fk_Turno_Sala2_idx` (`idSala` ASC),
  INDEX `fk_Turno_UC1_idx` (`codigoUC` ASC),
  INDEX `fk_Turno_Professor2_idx` (`UsernameProf` ASC),
  CONSTRAINT `fk_Turno_Sala2`
    FOREIGN KEY (`idSala`)
    REFERENCES `SM`.`Sala` (`idSala`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Turno_UC1`
    FOREIGN KEY (`codigoUC`)
    REFERENCES `SM`.`UC` (`codigoUC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Turno_Professor2`
    FOREIGN KEY (`UsernameProf`)
    REFERENCES `SM`.`Professor` (`Username`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SM`.`UC`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SM`.`UC` ;

CREATE TABLE IF NOT EXISTS `SM`.`UC` (
  `codigoUC` VARCHAR(45) NOT NULL,
  `Designaçao` VARCHAR(100) NOT NULL,
  `usernameRegente` VARCHAR(45) NULL,
  PRIMARY KEY (`codigoUC`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SM`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SM`.`Aluno` ;

CREATE TABLE IF NOT EXISTS `SM`.`Aluno` (
  `idAluno` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Trabalhador` TINYINT(1) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SM`.`Perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SM`.`Perfil` ;

CREATE TABLE IF NOT EXISTS `SM`.`Perfil` (
  `idPerfil` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SM`.`Registo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SM`.`Registo` ;

CREATE TABLE IF NOT EXISTS `SM`.`Registo` (
  `idTurno` VARCHAR(45) NOT NULL,
  `codigoUC` VARCHAR(45) NOT NULL,
  `idAluno` VARCHAR(45) NOT NULL,
  `idRegisto` INT NOT NULL,
  INDEX `fk_Registo_Turno2_idx` (`idTurno` ASC, `codigoUC` ASC),
  PRIMARY KEY (`idTurno`, `codigoUC`, `idRegisto`, `idAluno`),
  CONSTRAINT `fk_Registo_Turno2`
    FOREIGN KEY (`idTurno` , `codigoUC`)
    REFERENCES `SM`.`Turno` (`idTurno` , `codigoUC`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Registo_Aluno2`
    FOREIGN KEY (`idAluno`)
    REFERENCES `SM`.`Aluno` (`idAluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SM`.`Troca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SM`.`Troca` ;

CREATE TABLE IF NOT EXISTS `SM`.`Troca` (
  `idTroca` INT NOT NULL auto_increment,
  `idAluno` VARCHAR(45) NOT NULL,
  `idTurnoAtual` VARCHAR(45) NOT NULL,
  `idTurnoDesejado` VARCHAR(45) NOT NULL,
  `codigoUC` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTroca`),
  INDEX `fk_Troca_Aluno4_idx` (`idAluno` ASC),
  CONSTRAINT `fk_Troca_Aluno4`
    FOREIGN KEY (`idAluno`)
    REFERENCES `SM`.`Aluno` (`idAluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SM`.`Falta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `SM`.`Falta` ;

CREATE TABLE IF NOT EXISTS `SM`.`Falta` (
  `idFalta` INT NOT NULL auto_increment,
  `codigoUC` VARCHAR(45) NOT NULL,
  `idTurno` VARCHAR(45) NOT NULL,
  `idAluno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFalta`, `codigoUC`, `idAluno`),
  INDEX `fk_Falta_Aluno1_idx` (`idAluno` ASC),
  CONSTRAINT `fk_Falta_Aluno1`
    FOREIGN KEY (`idAluno`)
    REFERENCES `SM`.`Aluno` (`idAluno`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
