/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shiftmanagement.presentation;

import shiftmanagement.Business.*;

/**
 *
 * @author Tiago
 */
public class ConsultarUcLicenciatura extends javax.swing.JDialog {
    
    private ShiftManagement system;
    private String uc;
    
    /**
     * Creates new form ConsultarUcLicenciatura
     * @param parent
     * @param modal
     * @param s
     * @param uc
     */
    public ConsultarUcLicenciatura(java.awt.Frame parent, boolean modal, ShiftManagement s, String uc) {
        super(parent, modal);
        initComponents();
        this.system = s;
        this.uc = uc;
        atualizaJanela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeDaUc = new javax.swing.JLabel();
        designacaoUcField = new javax.swing.JTextField();
        codigoField = new javax.swing.JTextField();
        regField = new javax.swing.JTextField();
        nomeUc = new javax.swing.JLabel();
        codigoUC = new javax.swing.JLabel();
        profResponsavel = new javax.swing.JLabel();
        docentesUC = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nomeDaUc.setText("jLabel1");

        designacaoUcField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                designacaoUcFieldActionPerformed(evt);
            }
        });

        regField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regFieldActionPerformed(evt);
            }
        });

        nomeUc.setText("Designação");

        codigoUC.setText("Código");

        profResponsavel.setText("Professor Regente");

        docentesUC.setText("Equipa Docente");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(nomeDaUc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomeUc)
                            .addComponent(profResponsavel)
                            .addComponent(codigoUC)
                            .addComponent(docentesUC))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigoField)
                            .addComponent(regField)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(designacaoUcField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(131, 131, 131))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(nomeDaUc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(designacaoUcField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeUc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigoUC))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(profResponsavel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(docentesUC)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    public void atualizaJanela(){
        nomeDaUc.setText(uc);
        designacaoUcField.setText(uc);
        String codigo = this.system.getCodigoUc(uc);
        
    }
    
    private void designacaoUcFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_designacaoUcFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_designacaoUcFieldActionPerformed

    private void regFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigoField;
    private javax.swing.JLabel codigoUC;
    private javax.swing.JTextField designacaoUcField;
    private javax.swing.JLabel docentesUC;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomeDaUc;
    private javax.swing.JLabel nomeUc;
    private javax.swing.JLabel profResponsavel;
    private javax.swing.JTextField regField;
    // End of variables declaration//GEN-END:variables
}
