/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shiftmanagement.presentation;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import shiftmanagement.Business.ShiftManagement;
import shiftmanagement.Parser.Parser;

/**
 *
 * @author Tiago
 */
public class FrameMenuUCSMI extends javax.swing.JFrame {
    
    private ShiftManagement system;

    /**
     * Creates new form FrameMenuUCS
     * @param system
     */
    public FrameMenuUCSMI(ShiftManagement system) {
        initComponents();
        this.system = system;
        atualizaListas();
    }
    
    private void atualizaListas(){
        atualizaListaUcsLic();
        atualizaListaPerfis();
        atualizaListaUcsComp();
    }
    
    private void atualizaListaUcsLic(){
        DefaultListModel<String> lista = new DefaultListModel<>();
        ArrayList<String> ucs = this.system.getUcsLicPorCodENome();
        ucs.forEach((s) -> {
            lista.addElement(s);
        });
        ucsLicenciaturaList.setModel(lista);
    }
    
    private void atualizaListaPerfis(){
        DefaultListModel<String> lista = new DefaultListModel<>();
        ArrayList<String> perfis = this.system.getPerfisPorNome();
        perfis.forEach((s) -> {
            lista.addElement(s);
        });
        perfisList.setModel(lista);
    }
    
    private void atualizaListaUcsComp(){
        DefaultListModel<String> lista = new DefaultListModel<>();
        ArrayList<String> ucsComp = this.system.getUcsCompPorCodENome();
        ucsComp.forEach((s) -> {
            lista.addElement(s);
        });
        perfisList.setModel(lista);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ucsLicenciaturaList = new javax.swing.JList<>();
        consultarUcLicButton = new javax.swing.JButton();
        remUcLicButon = new javax.swing.JButton();
        addUcLicButton = new javax.swing.JButton();
        importUcLicButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        perfisList = new javax.swing.JList<>();
        consultarPerfilButton = new javax.swing.JButton();
        addPerfilButton = new javax.swing.JButton();
        remPerfilButton = new javax.swing.JButton();
        importPerfilButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ucsCompList = new javax.swing.JList<>();
        consultarUCCompButton = new javax.swing.JButton();
        addUcComptButton = new javax.swing.JButton();
        remUcCompButton = new javax.swing.JButton();
        importUcCompButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("Unidades Curriculares");

        ucsLicenciaturaList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(ucsLicenciaturaList);

        consultarUcLicButton.setText("Consultar UC");
        consultarUcLicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarUcLicButtonActionPerformed(evt);
            }
        });

        remUcLicButon.setText("Remover UC");
        remUcLicButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remUcLicButonActionPerformed(evt);
            }
        });

        addUcLicButton.setText("Adicionar UC");
        addUcLicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUcLicButtonActionPerformed(evt);
            }
        });

        importUcLicButton.setText("Importar UC's");
        importUcLicButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importUcLicButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addUcLicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(consultarUcLicButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(remUcLicButon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(importUcLicButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(consultarUcLicButton)
                        .addGap(18, 18, 18)
                        .addComponent(addUcLicButton)
                        .addGap(18, 18, 18)
                        .addComponent(remUcLicButon)
                        .addGap(18, 18, 18)
                        .addComponent(importUcLicButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("UC's de Licenciatura", jPanel1);

        perfisList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(perfisList);

        consultarPerfilButton.setText("Consultar Perfil");
        consultarPerfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarPerfilButtonActionPerformed(evt);
            }
        });

        addPerfilButton.setText("Adicionar Perfil");
        addPerfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPerfilButtonActionPerformed(evt);
            }
        });

        remPerfilButton.setText("Remover Perfil");
        remPerfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remPerfilButtonActionPerformed(evt);
            }
        });

        importPerfilButton.setText("Importar Perfis");
        importPerfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importPerfilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addPerfilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(remPerfilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(importPerfilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(consultarPerfilButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(consultarPerfilButton)
                .addGap(18, 18, 18)
                .addComponent(addPerfilButton)
                .addGap(18, 18, 18)
                .addComponent(remPerfilButton)
                .addGap(18, 18, 18)
                .addComponent(importPerfilButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Perfis de Mestrado", jPanel2);

        ucsCompList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(ucsCompList);

        consultarUCCompButton.setText("Consultar UC");
        consultarUCCompButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarUCCompButtonActionPerformed(evt);
            }
        });

        addUcComptButton.setText("Adicionar UC");
        addUcComptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUcComptButtonActionPerformed(evt);
            }
        });

        remUcCompButton.setText("Remover UC");
        remUcCompButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remUcCompButtonActionPerformed(evt);
            }
        });

        importUcCompButton.setText("Importar UC's");
        importUcCompButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importUcCompButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(importUcCompButton)
                    .addComponent(remUcCompButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(consultarUCCompButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addUcComptButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(84, 84, 84))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(consultarUCCompButton)
                        .addGap(18, 18, 18)
                        .addComponent(addUcComptButton)
                        .addGap(18, 18, 18)
                        .addComponent(remUcCompButton)
                        .addGap(18, 18, 18)
                        .addComponent(importUcCompButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("UC's Complementares", jPanel3);

        closeButton.setText("Fechar");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(closeButton)
                        .addGap(311, 311, 311))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(160, 160, 160))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(closeButton)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarUcLicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarUcLicButtonActionPerformed
        //botao consultar UC (Licenciatura)
        String uc = ucsLicenciaturaList.getSelectedValue();
        if(uc != null){
            FrameConsultarUc ucDeLicenciatura = new FrameConsultarUc(this.system, uc, 1);
            ucDeLicenciatura.setVisible(true);
        }
    }//GEN-LAST:event_consultarUcLicButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        //botao fechar
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void addUcLicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUcLicButtonActionPerformed
        // botao adicionar UC lic
        FrameAddUc addUcLic = new FrameAddUc(this.system, 1);
        addUcLic.setVisible(true);
    }//GEN-LAST:event_addUcLicButtonActionPerformed

    private void remUcLicButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remUcLicButonActionPerformed
        // botao remover
        String s = this.ucsLicenciaturaList.getSelectedValue();
        if(s!=null){
            s = s.substring(0, s.indexOf(" "));
            this.system.removeUc(s, 1, null);
        }
    }//GEN-LAST:event_remUcLicButonActionPerformed

    private void importUcLicButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importUcLicButtonActionPerformed
        // TODO add your handling code here:
        Parser p = new Parser(this.system);
        p.parseUcs();
        this.atualizaListaUcsLic();
    }//GEN-LAST:event_importUcLicButtonActionPerformed

    private void consultarUCCompButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarUCCompButtonActionPerformed
        // botao consultar uc complementar
        String uc = ucsCompList.getSelectedValue();
        if(uc != null){
            FrameConsultarUc consultarUC = new FrameConsultarUc(this.system, uc, 2);
            consultarUC.setVisible(true);
        }
    }//GEN-LAST:event_consultarUCCompButtonActionPerformed

    private void addUcComptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUcComptButtonActionPerformed
        //botao adicionar uc complementar
        FrameAddUc addUcLic = new FrameAddUc(this.system, 2);
        addUcLic.setVisible(true);
    }//GEN-LAST:event_addUcComptButtonActionPerformed

    private void remUcCompButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remUcCompButtonActionPerformed
        // botao remover
        String s = this.ucsCompList.getSelectedValue();
        if(s!=null){
            s = s.substring(0, s.indexOf(" "));
            this.system.removeUc(s, 2, null);
        }
    }//GEN-LAST:event_remUcCompButtonActionPerformed

    private void consultarPerfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarPerfilButtonActionPerformed
        // botao consultar perfil
        String perfil = this.perfisList.getSelectedValue();
        if(perfil != null){
            FrameConsultarPerfil consultarPerfil = new FrameConsultarPerfil(this.system, perfil);
            consultarPerfil.setVisible(true);
        }
    }//GEN-LAST:event_consultarPerfilButtonActionPerformed

    private void importUcCompButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importUcCompButtonActionPerformed
        // botao impotar ucs
        Parser p = new Parser(this.system);
        p.parseUcComp();
        this.atualizaListaUcsComp();
    }//GEN-LAST:event_importUcCompButtonActionPerformed

    private void importPerfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importPerfilButtonActionPerformed
        // TODO add your handling code here:
        Parser p = new Parser(this.system);
        p.parsePerfis();
        this.atualizaListaPerfis();
    }//GEN-LAST:event_importPerfilButtonActionPerformed

    private void addPerfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPerfilButtonActionPerformed
        //botao adicionar perfil
        FrameAddPerfil novoPerfil = new FrameAddPerfil(this.system);
        novoPerfil.setVisible(true);
    }//GEN-LAST:event_addPerfilButtonActionPerformed

    private void remPerfilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remPerfilButtonActionPerformed
        // botao remover Perfil
        String perfil = this.perfisList.getSelectedValue();
        if(perfil != null){
            int suc = this.system.removePerfil(perfil);
            if(suc != 0){
                JOptionPane.showMessageDialog (null, "Perfil removido com sucesso!", "Rip Perfil", JOptionPane.INFORMATION_MESSAGE);
            }
            else JOptionPane.showMessageDialog (null, "Erro! Perfil não removido!", "rip Perfil", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_remPerfilButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPerfilButton;
    private javax.swing.JButton addUcComptButton;
    private javax.swing.JButton addUcLicButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton consultarPerfilButton;
    private javax.swing.JButton consultarUCCompButton;
    private javax.swing.JButton consultarUcLicButton;
    private javax.swing.JButton importPerfilButton;
    private javax.swing.JButton importUcCompButton;
    private javax.swing.JButton importUcLicButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> perfisList;
    private javax.swing.JButton remPerfilButton;
    private javax.swing.JButton remUcCompButton;
    private javax.swing.JButton remUcLicButon;
    private javax.swing.JList<String> ucsCompList;
    private javax.swing.JList<String> ucsLicenciaturaList;
    // End of variables declaration//GEN-END:variables
}
